<div class="card" style="width: 18rem;">
  <img src="https://mediahub.seoul.go.kr/uploads/mediahub/2021/04/fIoyiYBFcMltsFcfRYSJRXSUEOCfAxuR.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="/view-details.php" class="btn btn-primary">상세페이지</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="https://mediahub.seoul.go.kr/uploads/mediahub/2021/04/fIoyiYBFcMltsFcfRYSJRXSUEOCfAxuR.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="/view-details.php" class="btn btn-primary">상세페이지</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="https://mediahub.seoul.go.kr/uploads/mediahub/2021/04/fIoyiYBFcMltsFcfRYSJRXSUEOCfAxuR.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="/view-details.php" class="btn btn-primary">상세페이지</a>
  </div>
</div>
<div class="card" style="width: 18rem;">
  <img src="https://mediahub.seoul.go.kr/uploads/mediahub/2021/04/fIoyiYBFcMltsFcfRYSJRXSUEOCfAxuR.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="/view-details.php" class="btn btn-primary">상세페이지</a>
  </div>
</div>

<style>
    .card{
        display:inline-block;
    }
</style>